//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GivskudApp.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GivskudApp.AppResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        public static string AnimalDetailsContinent {
            get {
                return ResourceManager.GetString("AnimalDetailsContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eats.
        /// </summary>
        public static string AnimalDetailsEats {
            get {
                return ResourceManager.GetString("AnimalDetailsEats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string AnimalDetailsSpecies {
            get {
                return ResourceManager.GetString("AnimalDetailsSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AnimalDetailsStatus {
            get {
                return ResourceManager.GetString("AnimalDetailsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Information.
        /// </summary>
        public static string AnimalGuidePageBtnInformation {
            get {
                return ResourceManager.GetString("AnimalGuidePageBtnInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Quiz.
        /// </summary>
        public static string AnimalGuidePageBtnQuiz {
            get {
                return ResourceManager.GetString("AnimalGuidePageBtnQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me the map.
        /// </summary>
        public static string AnimalGuidePageBtnShowOnMap {
            get {
                return ResourceManager.GetString("AnimalGuidePageBtnShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen the.
        /// </summary>
        public static string AnimalGuidePageHeadline01 {
            get {
                return ResourceManager.GetString("AnimalGuidePageHeadline01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to know first about this animal?.
        /// </summary>
        public static string AnimalGuidePageHeadline02 {
            get {
                return ResourceManager.GetString("AnimalGuidePageHeadline02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults 2019.
        /// </summary>
        public static string BuyTicketsAdults {
            get {
                return ResourceManager.GetString("BuyTicketsAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Checkout.
        /// </summary>
        public static string BuyTicketsCheckout {
            get {
                return ResourceManager.GetString("BuyTicketsCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children (3-11 years) 2019.
        /// </summary>
        public static string BuyTicketsChildren {
            get {
                return ResourceManager.GetString("BuyTicketsChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Tickets.
        /// </summary>
        public static string BuyTicketsHeader {
            get {
                return ResourceManager.GetString("BuyTicketsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newborns (0-2 years) 2019.
        /// </summary>
        public static string BuyTicketsNewborns {
            get {
                return ResourceManager.GetString("BuyTicketsNewborns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Map.
        /// </summary>
        public static string ContactUsBtnMap {
            get {
                return ResourceManager.GetString("ContactUsBtnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would rather talk to us face to face, see our map and find us in our zoo..
        /// </summary>
        public static string ContactUsFooter {
            get {
                return ResourceManager.GetString("ContactUsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Events, Schools, and Accommodation.
        /// </summary>
        public static string ContactUsGroupAndEvents {
            get {
                return ResourceManager.GetString("ContactUsGroupAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUsHeadline {
            get {
                return ResourceManager.GetString("ContactUsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information and Tickets.
        /// </summary>
        public static string ContactUsInfoAndTickets {
            get {
                return ResourceManager.GetString("ContactUsInfoAndTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The phones are unavailable from December 22nd to January 1st.
        /// </summary>
        public static string ContactUsPhoneTableDescription {
            get {
                return ResourceManager.GetString("ContactUsPhoneTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Hours.
        /// </summary>
        public static string ContactUsPhoneTableHeadline {
            get {
                return ResourceManager.GetString("ContactUsPhoneTableHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are available if you have any questions.
        /// </summary>
        public static string ContactUsSubheadline {
            get {
                return ResourceManager.GetString("ContactUsSubheadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizzes.
        /// </summary>
        public static string GamesBtnQuizzes {
            get {
                return ResourceManager.GetString("GamesBtnQuizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string GeneralYears {
            get {
                return ResourceManager.GetString("GeneralYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youngs.
        /// </summary>
        public static string GeneralYoungs {
            get {
                return ResourceManager.GetString("GeneralYoungs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Park Areas.
        /// </summary>
        public static string GuidedTourAreas {
            get {
                return ResourceManager.GetString("GuidedTourAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome toGivskud Zoo! I am your guide, Anna! I will be helping you on your trip through the zoo. What would you like to see first?.
        /// </summary>
        public static string GuidedTourIntroduction {
            get {
                return ResourceManager.GetString("GuidedTourIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Games.
        /// </summary>
        public static string GuidedTourQuizzes {
            get {
                return ResourceManager.GetString("GuidedTourQuizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Map.
        /// </summary>
        public static string HomepageBtnMap {
            get {
                return ResourceManager.GetString("HomepageBtnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Program.
        /// </summary>
        public static string HomepageBtnProgram {
            get {
                return ResourceManager.GetString("HomepageBtnProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guided Tour.
        /// </summary>
        public static string HomepageBtnTour {
            get {
                return ResourceManager.GetString("HomepageBtnTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string NavigationAnimals {
            get {
                return ResourceManager.GetString("NavigationAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Tickets.
        /// </summary>
        public static string NavigationBuyTickets {
            get {
                return ResourceManager.GetString("NavigationBuyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string NavigationContact {
            get {
                return ResourceManager.GetString("NavigationContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Games.
        /// </summary>
        public static string NavigationGames {
            get {
                return ResourceManager.GetString("NavigationGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string NavigationHomepage {
            get {
                return ResourceManager.GetString("NavigationHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string NavigationNews {
            get {
                return ResourceManager.GetString("NavigationNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Pass.
        /// </summary>
        public static string NavigationSeasonPass {
            get {
                return ResourceManager.GetString("NavigationSeasonPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pass with the ID / the pass you saved seems to be invalid. Please try again..
        /// </summary>
        public static string NotificationInvalidPass {
            get {
                return ResourceManager.GetString("NotificationInvalidPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with your internet connection. Please connect your device to the internet.
        /// </summary>
        public static string NotificationNoInternet {
            get {
                return ResourceManager.GetString("NotificationNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content used is outdated. Please connect your device to the internet to see the newest content.
        /// </summary>
        public static string NotificationOutdatedContent {
            get {
                return ResourceManager.GetString("NotificationOutdatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Games.
        /// </summary>
        public static string QuizBtnBackToGames {
            get {
                return ResourceManager.GetString("QuizBtnBackToGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Question.
        /// </summary>
        public static string QuizBtnNextQuestion {
            get {
                return ResourceManager.GetString("QuizBtnNextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not bad! You will get them next time, do not worry!.
        /// </summary>
        public static string QuizEndTitle01 {
            get {
                return ResourceManager.GetString("QuizEndTitle01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admirable! Take one of our guided tours to make your knowledge better..
        /// </summary>
        public static string QuizEndTitle02 {
            get {
                return ResourceManager.GetString("QuizEndTitle02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is very good result! You are a smart monkey!.
        /// </summary>
        public static string QuizEndTitle03 {
            get {
                return ResourceManager.GetString("QuizEndTitle03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your score is perfect!.
        /// </summary>
        public static string QuizEndTitle04 {
            get {
                return ResourceManager.GetString("QuizEndTitle04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By scanning the code you get to your current point in the tour guide..
        /// </summary>
        public static string ScannerPageDescription {
            get {
                return ResourceManager.GetString("ScannerPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the code on an info stand..
        /// </summary>
        public static string ScannerPageTitle {
            get {
                return ResourceManager.GetString("ScannerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired On:.
        /// </summary>
        public static string SeasonPassAcquiredOn {
            get {
                return ResourceManager.GetString("SeasonPassAcquiredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pass.
        /// </summary>
        public static string SeasonPassBtnAdd {
            get {
                return ResourceManager.GetString("SeasonPassBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Pass.
        /// </summary>
        public static string SeasonPassBtnRemove {
            get {
                return ResourceManager.GetString("SeasonPassBtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This ID can be found on the physical card or a receipt acquired by purchasing the pass..
        /// </summary>
        public static string SeasonPassDescription {
            get {
                return ResourceManager.GetString("SeasonPassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pass Details.
        /// </summary>
        public static string SeasonPassHeadline01 {
            get {
                return ResourceManager.GetString("SeasonPassHeadline01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Season Pass.
        /// </summary>
        public static string SeasonPassHeadline02 {
            get {
                return ResourceManager.GetString("SeasonPassHeadline02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From:.
        /// </summary>
        public static string SeasonPassValidFrom {
            get {
                return ResourceManager.GetString("SeasonPassValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To:.
        /// </summary>
        public static string SeasonPassValidTo {
            get {
                return ResourceManager.GetString("SeasonPassValidTo", resourceCulture);
            }
        }
    }
}
